### ISSUE TITLE
Incompatible with PHPStorm

### ISSUE THREAD

**Issue by drobinson** [naotaka/ClipMenu#1]
I haven't spent enough time on this to really give a very helpful description, but basically the problem is that when using ClipMenu I do not get what I expect when pasting into PHPStorm.  It seems PHPStorm is trying to be smart and have its own clipboard history.  This is most likely a PHPStorm issue only, but I would like to know how this application works when pasting a selected history item.  Does it move the selected entry into the system clipboard and then execute ⌘-V?

PHPStorm will only paste the last thing copied from within the editor until I simply switch away from and back to the editor.  After that, ClipMenu works as expected until I copy something from within the editor.

**Comment by nebbian** [comment]
A possible workaround is detailed here:
http://youtrack.jetbrains.com/issue/IDEA-114252#comment=27-678923

**Comment by hanoii** [comment]
as mentioned in that issue, it is bug in java in general, I wonder if clipmenu could do a simple workaround. I know it's not its place, but it may not harm, could it possible unfocus the active window, focus something else, and then regain the focus to the active window? that might fix it.

**Comment by tomschlick** [comment]
+1 for a fix/workaround on this. Even though its not a direct issue with ClipMenu its not fixable right now by the PHPStorm so if there is an easy work around it would help out a lot.

**Comment by naotaka** [comment]
I read some discussions about this issue include @nebbian's posted one, and tried 30 days demo version of PHPStorm 7.1.4 by myself. I realized the problem.

I think this should be solved by JetBrains' guys but it seems that it's not so easy problem for them.

I might try to solve this, but sorry for you guys, its priority is not so high. I would decide it after the fix to be compatible with Yosemite.

Thank you for your patience.

**Comment by tenitski** [comment]
It looks like ClipMenu works fine with my PHPStorm 8

**Comment by tenitski** [comment]
Actually it is still broken in PHPStorm 8, sorry for the prev confusing comment

**Comment by honzadavidcz** [comment]
The same problem, but with ClipboardHistory in Yosemite.

**Comment by naotaka** [comment]
I have built a testing version for this issue. Please try it, and give me your feedback.

http://www.clipmenu.com/blog/2014/10/31/compatibility-testing-with-jetbrains-ides/

**Comment by senechaux** [comment]
It works great! The bad thing is we lost a lot of preferences.

**Comment by shirki** [comment]
Hi @naotaka , thanks for this version. Like @senechaux I lost preferences and back history when testing this, which is a shame, but not too big of a problem.
However, in my case what it does is simply lets the JIDea clipboard manager take over. Which is not my intention.
I will go back to trying the JIdea workaround (see http://stackoverflow.com/questions/26611642/external-clipboard-manager-breaking-in-jidea/26611643#26611643 ) and see if that solves it.

In any case -- appreciate you looking into this!!!

**Comment by drobinson** [comment]
@shirki This seems to work for me in PHPStorm 8.0.3 - and seems to be the most "correct" way to solve this...there should be a user setting in PHPStorm for "Use System Clipboard"

@naotaka if you agree, I would close this issue.  Thanks for the help.

**Comment by tenitski** [comment]
Confirming that it fixed the issue for me too
